
SELECT NVL (SUM (D.ALLOCATED_AMOUNT), 0) AS Balance
FROM flexcube.IATM_ASSET_FUND_LINK_MASTER M1,
     flexcube.IATM_ASSET_FUND_LINK D,
     flexcube.CLTB_ACCOUNT_APPS_MASTER CL,
     flexcube.CLTM_PRODUCT PRD
WHERE M1.EFF_DATE =
         (SELECT MAX (M2.EFF_DATE)
          FROM flexcube.IATM_ASSET_FUND_LINK_MASTER M2
          WHERE     M2.ASSET_CODE = M1.ASSET_CODE
                AND M2.ASSET_CCY = M1.ASSET_CCY
                AND M2.SUKKUKH_CODE = M1.SUKKUKH_CODE
                AND M2.EFF_DATE <= TO_DATE (:PM_DATE, 'YYYY-MM-DD'))
      AND D.FUND_ID = :PM_FUND_ID
      AND M1.ASSET_CODE = D.ASSET_CODE
      AND M1.ASSET_CCY = D.ASSET_CCY
      AND M1.SUKKUKH_CODE = D.SUKKUKH_CODE
      AND D.ASSET_CODE = CL.ACCOUNT_NUMBER
      AND CL.PRODUCT_CODE = PRD.PRODUCT_CODE
      AND PRD.FA_PRODUCT IS NOT NULL;
